spring:
    ## DB接続情報
    dataSource:
        url: jdbc:mysql://awseb-e-7y4ayv2pg4-stack-awsebrdsdatabase-f4ottw1nwrww.crdfsuxjspib.ap-northeast-1.rds.amazonaws.com:3306/ebdb
        username: odetatsu
        password: D1OJGVyUDXWGzpc3osaO
        driver-class-name: com.mysql.cj.jdbc.Driver
    sql.init.mode: never
    jpa.hibernate.ddl-auto: update
# サーバー設定
server:
    port: 5000
    